SET NAMES UTF8;
DROP DATABASE IF EXISTS xiaofeiniu;
CREATE DATABASE xiaofeiniu CHARSET=UTF8;
USE xiaofeiniu;
CREATE TABLE xfn_admin(
  aid  INT PRIMARY KEY AUTO_INCREMENT,
  aname VARCHAR(32),
  apwd VARCHAR(64),
);
INSERT INTO xfn_admin VALUES
  ();
CREATE TABLE xfn_settings(
  sid INT PRIMARY KEY AUTO_INCREMENT,

)



